### ISSUE TITLE
Tracking issue for improvements to Rust itself

### ISSUE THREAD

**Issue by retep998** [rust-windows/wg#3]
This issue will track every issue and PR related to improving Rust itself on Windows. Please keep discussion of specific issues to separate issues. Comments here should only be to suggest changes to this list.

### Not started
* [ ] Pure Rust Windows target with no external C toolchain dependency, taking advantage of LLD and `raw-dylib`.
* [ ] [Add debug CRT option.](https://github.com/rust-lang/rust/issues/39016) Has some old stagnant PRs that can be revived to easily get this going.
* [ ] Do something to finally stabilize the functionality of `kind="static-nobundle"` in some form.
* [ ] [Some way to do Structured Exception Handling directly in Rust.](https://github.com/rust-lang/rust/issues/38963)
* [ ] Spawning processes needs a lot of work on Windows
  * [ ] [Inheriting handles is terrible and should be changed](https://github.com/rust-lang/rust/issues/38227)
  * [ ] [When `PATH` is modified `Command` does its own logic to locate the exe to match unix behavior and it is different from what Windows does.](https://github.com/rust-lang/rust/issues/37519)
  * [ ] Provide way to override the entire command line string on Windows.
* [ ] Let build scripts specify custom linker arguments.
* [ ] Native support for resource files and manifests in Rust.
* [ ] Ability to link to object files directly.
* [ ] [Fix `env_clear` on Windows.](https://github.com/rust-lang/rust/issues/31259)

### Proposal in progress
* [ ] A way to specify which version of Windows your program requires and generating optimal code based on that. [Pre-RFC on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/242869-t-compiler.2Fwindows/topic/(Pre-RFC.3F).20target-api.2Fos-version)

### Implementation in progress
* [ ] [`#[link(kind="raw-dylib")]`](https://github.com/rust-lang/rust/issues/58713)

### Completed

**Comment by Lokathor** [comment]
* [ ] [Tracking issue for RFC 2627: #[link(kind="raw-dylib")]](https://github.com/rust-lang/rust/issues/58713)

**Comment by crlf0710** [comment]
- [ ] The mountain of [Rust, Windows, and MSVC](https://github.com/rust-lang/rfcs/issues/1061)

**Comment by matklad** [comment]
- [ ] [`std::fs::revome_dir_all()` doesn't work on windows](https://github.com/rust-lang/rust/issues/29497)

**Comment by nico-abram** [comment]
@retep998 env_clear seems to be fixed: https://github.com/rust-lang/rust/issues/31259

Just wanted to mention it in case you wanted to update the checkbox in your comment

**Comment by tbu-** [comment]
@retep998 `#[link(kind = "raw-dylib")]` has also stabilized for a long time already.
